package com.james;

public class Appointment {
    /*
    TEMPORARY CLASS FOR DEBUGGING STATE MANAGER
    DO NOT MODIFY THIS FILE, IT WILL BE DELETED LATER.
    WILL USE USER CLASS IMPLEMENTED BY ANOTHER TEAM MEMBER INSTEAD
    */
}